# Tensors

텐서는 행렬, 배열과 유사한 특수 자료구조.<br>
파이토치에서는 입력, 출력 및 모델의 파라미터를 encoding하는 역할을 한다.<br>
즉, tensor는 입력, 출력, 파라미터를 저장하는 그릇의 역할

In [1]:
import torch
import numpy as np

## tensor initialization

tensor를 초기화하는 방법은 다양함

### directly from data

data를 바로 tensor로 만들 수 있으며, 데이터 타입은 자동으로 추정된다.

In [2]:
data = [[1,2] , [3,4]]
x_data = torch.tensor(data)

### From a Numpy array

Numpy array를 Tensor로 변환할 수 있다.

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

### From another tensor

재정의(override)된 경우가 아니라면, 다른 tensor의 특징(shape, datatype)을 보존한 새로운 tensor를 만들 수 있다.<br>


In [4]:
x_ones = torch.ones_like(x_data) # retain properties of origin tensor
print(f"Ones Tensor: \n {x_ones} \n") # f in print make object to str

x_rand = torch.rand_like(x_data, dtype=torch.float) # override the datatype
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2811, 0.2313],
        [0.7028, 0.8177]]) 



### With random or constant values

tensor의 dimension을 명시하는 tuple형 변수 shape로 원하는 dimension에 해당하는 tensor를 생성할 수 있다.

In [5]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.4224, 0.2681, 0.6200],
        [0.7118, 0.1578, 0.2343]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## Tensor Attibutes

Tensor가 가지고 있는 attributes는 shape, datatype, 그리고 tensor가 저장되어있는 device가 있음

In [6]:
tensor = torch.rand(3,4)
tensor_c = torch.rand(3,4).cuda()

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
print(f"Device tensor_cuda is stored on: {tensor_c.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Device tensor_cuda is stored on: cuda:0


## Tensor Operations

Transposing, indexing, slicing, mathematical operations, linear algebra(related vector and matricies), random sampling 등등 100개가 넘는 연산이 존재한다<br>
이러한 연산들은 GPU로 구동가능하며, cuda 구동이 가능한지의 여부는 다음과 같이 확인할 수 있다.

In [7]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


### Standard numpy-like indexing and slicing

In [8]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0 # 2nd column changed from '1' to '0'
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


torch.cat 함수를 이용해 torch를 join(concatenate)할 수 있으며, 다른 방버으로는 'torch.stack'이 존재한다

In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### Multiplying Tensors

tensor를 element wise로 곱하는 방법에는 tensor.mul 연산과 * 연산이 있는데, 보통 tensor 내장함수를 사용하는 것이 computational complxity의 측면에서 효율적이다.

In [10]:
# element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)}\n")
# Alternative syntax
print(f"tensor * tensor \n {tensor * tensor}\n")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])



서로 다른 두 tensor의 곱은 다음과 같다

In [11]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax
print(f"tensor @ tensor \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In-place 연산은 실제 tensor의 값을 바꾸는 연산을 한다. 기호는 연산뒤에 '_' 를 붙인다.

In [12]:
print(tensor, "\n")
tensor.add(5)
print("After add \n", tensor) # 텐서의 값은 바뀌지 않는다
tensor.add_(5)
print("\nAfter inplace add \n", tensor) # 텐서에 연산이 적용된다

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

After add 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

After inplace add 
 tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridge with NumPy

CPU로 처리되는 텐서와 Numpy array는 같은 메모리 공간을 공유한다.<br>

### Tensor to Numpy array

In [13]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


Tensor의 변환은 numpy에도 반영된다.

In [14]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### Numpy array to Tensor

In [15]:
n = np.ones(5)
t = torch.from_numpy(n)

Numpy의 변환 또한 Tensor에 적용된다.

In [16]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
